@host=http://localhost:5000/api
# @name health
GET http://localhost:5000/
Content-Type: application/json 
###

# @name signup
POST {{host}}/signup
Content-Type: application/json

{
    "firstName": "john",
    "lastName": "doe",
    "password": "",
    "email": "johndoe@gmail.com",
    "phoneNumber": "33728394029"    
}
###

# @name login
POST {{host}}/login
Content-Type: application/json

{
    "password": "12345",
    "email": "johndoe@gmail.com",
    "phoneNumber": "33728394029"    
}