@host=http://localhost:5000/api
# @name health
GET http://localhost:5000/
Content-Type: application/json 
###

# @name signup
POST {{host}}/signup
Content-Type: application/json

{
    "firstName": "john",
    "lastName": "doe",
    "password": "",
    "email": "johndoe@gmail.com",
    "phoneNumber": "52000000"    
}
###

# @name login
# @prompt email
# @prompt pass
POST {{host}}/login
Content-Type: application/json

{
    "password": "{{pass}}",
    "email": "{{email}}"
}
###
@userId = {{login.response.body.profile.id}}

# @name GetUserProfile
GET {{host}}/users/profile
###

# @name GetUserTeams
GET {{host}}/users/{{userId}}/teams
###

# @name CreateTeam
POST {{host}}/teams
Content-Type: application/json

{
    "name": "devops 6",
    "displayName": "devops",
    "email": "devops@gmail.com",
    "ownerId": "{{userId}}"
}
###

@teamId = {{CreateTeam.response.body.team.id}}
# @name UpdateTeam
PUT {{host}}/teams/{{teamId}}
Content-Type: application/json

{
    "name": "devops up",
    "displayName": "devops",
    "email": "devops@gmail.com"
}
###

# @name GetTeam
GET {{host}}/teams/{{teamId}}
###

# @name AddAgentToTeam
POST {{host}}/teams/{{teamId}}/agents
Content-Type: application/json

{
    "userId": "{{userId}}",
    "teamId": "{{teamId}}",
    "roleName": "admin"
}
###

# @name GetTeamAgents
GET {{host}}/teams/{{teamId}}/agents
###

# @name UpdateTeamAgent
PUT {{host}}/teams/{{teamId}}/agents
Content-Type: application/json

{
    "userId": "{{userId}}",
    "teamId": "{{teamId}}",
    "roleName": "agent"
}
###

# @name DeleteTeam
DELETE {{host}}/teams/{{teamId}}
###
# @name RemoveAgentFromTeam
DELETE  {{host}}/teams/{{teamId}}/agents
Content-Type: application/json

{
    "userId":"{{userId}}",
    "teamId": "{{teamId}}"
}
###

# @name CreateTicket
POST {{host}}/tickets
Content-Type: application/json

{
    "subject":"test",
    "requesterId":"{{userId}}",
    "agentId":"{{userId}}",
    "teamId":"{{teamId}}",
    "description": "{{teamId}}",
    "status": "OPEN"
}
###
@ticketId = {{CreateTicket.response.body.ticket.id}}

# @name GetTicket
GET {{host}}/tickets/{{ticketId}}
###

# @name UpdateTicketAgent
PATCH {{host}}/tickets/{{ticketId}}/agent
Content-Type: application/json

{
    "agentId": "{{userId}}"
}
###

# @name UpdateTicketStatus
PATCH {{host}}/tickets/{{ticketId}}/status
Content-Type: application/json

{
    "ticketId": "{{ticketId}}",
    "newStatus": "ON_HOLD",    
    "oldStatus": "CLOSED",
    "userId": "{{userId}}"
}
###

# @name getTicketLogs
GET {{host}}/tickets/{{ticketId}}/logs
###

# @name getTicketComments
GET {{host}}/tickets/{{ticketId}}/comments
###

# @name DeleteTicket
DELETE {{host}}/tickets/{{ticketId}}/

###
# @name CreateTicketComment
POST {{host}}/tickets/{{ticketId}}/comments
Content-Type: application/json

{
    "ticketId":"{{ticketId}}",
    "userId":"{{userId}}",
    "body": "test comment"
}
###